- hosts: [terraform_ansible]
  tasks:
    - name: criando o arquivo
      copy:
        dest: /home/ubuntu/index.html
        content: <h1> Feito com terraform-ansible - Teste de Servidor</h1>
    
    - name: criando servidor
      shell: "nohup busybox httpd -f -p 8080 &"